### ISSUE TITLE
Handle test/QA data properly

### ISSUE THREAD

**Issue by Dantemss** [openstax/biglearn-sparfa-server#53]
Currently QA/demo data in production can reduce the accuracy of the SPARFA algorithms by feeding them bad/random data. Figure out a way to mark all QA/demo accounts and courses as test accounts/courses and then isolate them from the real data in sparfa-server. Might need to retroactively fix data already entered into Biglearn.

Kevin favors separating test/demo data completely from real data based on fields we would add to the tables so they never affect each other.

##Acceptance Criteria
Data marked as test:

- any accounts in PRODUCTION used by QA marked as test
- any courses in PRODUCTION used by QA need to marked as test, even old ones
- future accounts in PRODUCTION used by QA or demo need to be marked as test
- accounts checkbox needs to be fixed so we can mark as test user (card in BIT -- make hi priority) 
- Needs to be done by end of Q4/beginning of Q1 2019.

How do we find out which account in PRODUCTION are used by QA and Demo?
- Denver University
- OpenStax University 
- Rice University (might not be test)
- Automation
- Test University 
- emails might be rice, mailinator, guerillamail, sharklazers, restmail 
- teacher ##, student ##
- Hansolo, Josie Chu, Iris West, Eliza Hamilton, Juliet
- nathanstitt, carlycurran (admin access) 
- 3815, 3907, 4463, 4621, 4664, 4460, 4488, 4132, 4495, 3960, 3879, 4209, 4095, 3954, 4564, 4706, 4540

Fix test checkbox
Spreadsheet of above 
Mark as test
Dante find test accounts and mark related courses as test with query (have some CS users joined courses) 
Dante has to go back and adjust BL to not pull from test accounts (retroactive) 

### Checklist for Done
1A-DEFINE
- [x] Description is complete 
- [x] High-level natural language acceptance tests are complete
- [x] If UX design is needed then the UX label is added
- [x] If UX design is needed then the UX LoFi Design is completed, approved by the Product Manager, and added to the issue.
- [x] A high-level solution (development approach for the code change) is added to the issue
- [x] If prototype code is generated, it is linked to the issue.
- [x] If tech briefs are generated, they are linked to the issue.

1B-DECOMP
  - [x] The work is broken into reasonable and consistent work items, and work item issues created. The work item issues are moved below the Done marker in the Decomp column.
  - [ ] Estimate is updated for the work item issues.
  - [ ] If there is a parent story epic issue, it is linked with the child work item issues and moved to the Epic column.
  - [ ] If an issue is included in a product phase, then Release is selected.

1C-DESIGN
  - [ ] The UX HiFi Design is complete, approved by the Product Manager, and added to the issue.
  - [ ] Distilled acceptance tests are added to the issue.
  - [ ] Automated testing criteria are added to issue.
  - [ ] The solution is updated.

2A-CODE
  - [ ] A pull request is opened, the automated pull request checks pass, and the change has been approved by other developers.
  - [ ] The acceptance tests are finalized in "Given / When / Then" format.
  - [ ] Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.

4A-UX REVIEW
  - [ ] The pull request is merged into master, and the change branch is deleted.

5A-FUNCT VER
  - [ ] All the acceptance tests for this issue pass.

5C-REGRESSION
  - [ ] The test plan in testrail passes.
  - [ ] Blessing from Product Manager that the release is good to go.

5D-READY TO BE DEPLOYED
  - [ ] Production is updated and verified.
  - [ ] All issues in the release are closed.

**Comment by carlycurran** [comment]
This includes marking as test: 
- accounts used by QA marked as test
- courses QA currently has need to marked as test, even old ones
- future accounts need to be marked as test 
- accounts checkbox needs to be fixed so we can mark as test user

Needs to be done by end of Q4/beginning of Q1 2019.

**Comment by carlycurran** [comment]
I went through a number of accounts and courses and marked them as test. Debshila has not seen much weird data show up in her production data sets, so I am going to mark this as done for now and close. We can revisit if we run into problems again down the road.
